class Dict:
    def __init__(self):
        self.books = []

        self.books.append(["genesis", "gn", "gen"])
        self.books.append(["exodus", "ex"])
        self.books.append(["leviticus","lev"])
        self.books.append(["numbers", "nu"])
        self.books.append(["deuteronomy","deut"])
        self.books.append(["joshua"])
        self.books.append(["judges"])
        self.books.append(["ruth"])
        self.books.append(["1 samuel", "1sam"])
        self.books.append(["2 samuel", "2sam"])
        self.books.append(["1 kings"])
        self.books.append(["2 kings"])
        self.books.append(["1 chronicles", "1chron"])
        self.books.append(["2 chronicles", "2chron"])
        self.books.append(["ezra"])
        self.books.append(["nehemiah","neh"])
        self.books.append(["esther"])
        self.books.append(["job"])
        self.books.append(["psalms"])
        self.books.append(["proverbs","prov"])
        self.books.append(["ecclesiastes", "ecc", "ec"])
        self.books.append(["song of solomon", "song"])
        self.books.append(["isaiah"])
        self.books.append(["jeremiah"])
        self.books.append(["lamentations", "lam"])
        self.books.append(["ezekiel"])
        self.books.append(["daniel"])
        self.books.append(["hosea"])
        self.books.append(["joel"])
        self.books.append(["amos"])
        self.books.append(["obadiah"])
        self.books.append(["jonah"])
        self.books.append(["micah"])
        self.books.append(["nahum"])
        self.books.append(["habakkuk", "hab", "hb"])
        self.books.append(["zephaniah", "zeph", "zep", "zp"])
        self.books.append(["haggai", "hag", "hg"])
        self.books.append(["zechariah", "zech", "zc"])
        self.books.append(["malachi", "mal", "ml"])
        self.books.append(["matthew", "mat"])
        self.books.append(["mark"])
        self.books.append(["luke"])
        self.books.append(["john"])
        self.books.append(["acts"])
        self.books.append(["romans", "roman"])
        self.books.append(["1 corinthians", "1cor"])
        self.books.append(["2 corinthians", "2cor"])
        self.books.append(["galatians", "gal", "gl", "galatian"])
        self.books.append(["ephesians", "eph", "ephesian"])
        self.books.append(["philippians", "philippian"])
        self.books.append(["colossians", "col", "colossian"])
        self.books.append(["1 thessalonians", "1thess"])
        self.books.append(["2 thessalonians", "2thess"])
        self.books.append(["1 timothy", "1tim"])
        self.books.append(["2 timothy", "2tim"])
        self.books.append(["titus"])
        self.books.append(["philemon"])
        self.books.append(["hebrews", "hebrew", "heb"])
        self.books.append(["james"])
        self.books.append(["1 peter", "1 peters", "1pet"])
        self.books.append(["2 peter", "2 peters", "2pet"])
        self.books.append(["1 john", "1john", "1jon", "1joh"])
        self.books.append(["2 john", "2john", "2jon", "2joh"])
        self.books.append(["3 john", "3john", "3jon", "3joh"])
        self.books.append(["jude"])
        self.books.append(["revelation", "revelations", "rev"])
